import manifest from "@/data/project-images.json";

// Responsive sources for a project screenshot generated by `npm run images`
// (scripts/project-images.mjs): AVIF and WebP at several widths, plus the
// original size so the browser reserves the space before the image arrives.

type Entry = { width: number; height: number; widths: number[] };
const IMAGES = manifest as Record<string, Record<string, Entry>>;

export interface Picture {
  avif: string;
  webp: string;
  /** Smallest WebP, for browsers without srcset support. */
  src: string;
  width: number;
  height: number;
}

export function picture(project: string, name: string): Picture | null {
  const e = IMAGES[project]?.[name];
  if (!e) return null;
  const set = (ext: string) => e.widths.map((w) => `/projects/${project}/${name}-${w}.${ext} ${w}w`).join(", ");
  return { avif: set("avif"), webp: set("webp"), src: `/projects/${project}/${name}-${e.widths[0]}.webp`, width: e.width, height: e.height };
}
